apiVersion: v1
kind: Pod
metadata:
  name: mysql-db-pod
  namespace: sqldb
spec:
  containers:
  - name: mysql-xinyueli
    image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2:my_db
    env:
    - name: MYSQL_ROOT_USER
      value: "root"
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306